### PR TITLE
Fix #32

### LINKED ISSUE #32: GetText() not working
For whatever reason PluginData.Editor.GetText() seems to always return an empty string. SetText() works just fine though, so I don't think the issue is on my end. Even after setting the text, GetText() still returns an empty string btw.

### PR DESCRIPTION
**Pull request by Mysterium-Mystery**

### CODE REVIEW

File: lib/Plugin/ScintillaGateway.cs [hunk 1]
```diff
@@ -125,7 +125,7 @@ private unsafe string GetNullStrippedStringFromMessageThatReturnsLength(SciMsg m
             byte[] textBuffer = new byte[length];
             fixed (byte* textPtr = textBuffer)
             {
-                SendMessage(_scintilla, msg, wParam, (IntPtr)textPtr);
+                SendMessage(_scintilla, msg, (wParam == UIntPtr.Zero ? (UIntPtr)length : wParam), (IntPtr)textPtr);
```
Comment (rdipardo) [inline lib/Plugin/ScintillaGateway.cs:128]: *Re. style:* Visual Studio suggests the outer parentheses can be removd:

vs code hint IDE0047

Comment (Mysterium-Mystery) [reply lib/Plugin/ScintillaGateway.cs]: I did notice that but I thought I'd just leave it like you suggested. Thought it might be for readability or something. Either way, I removed them now
